# Generated by Django 5.0.1 on 2024-01-11 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='phone',
            new_name='mobile_no',
        ),
    ]
